### ISSUE TITLE
Latest dialect update breaks MessageTrajectoryRepresentationWaypoints parsing

### ISSUE THREAD

**Issue by ebudan** [gswly/gomavlib#1]
In case of ardupilotmega/dialect.go, the following has been added to line 7108:

```
	Command [5]MAV_CMD `mavenum:"uint16"`
```

The top level dialect.go balks at this on line 160, expecting a Command enum based on the `mavenum` annotation, not an array. 

The result is a run-time panic upon dialect initialization.

**Comment by gswly** [comment]
Hi, thanks for the feedback.
Dialects are updated very often, and this breaks dependent libraries. That's the reason why dialects are merely a plugin in Gomavlib, while in other libraries they are used to generate the entire library (pymavlink, c) , and in my opinion this is a error.

Anyway, i fixed the issue and made sure this is signaled by CI next time, since:
* i added tests to every dialect in 87dd2090
* i added a unit test of enums of arrays in b9823868
